### ISSUE TITLE
It's not possible to cancel joining a room

### ISSUE THREAD

**Issue by vigejolla** [thigg/sfos-hydrogen#6]
From the top right + -button, select "join room". Now, you are faced with a text field for entering the id of the room you want to join. And there is no way to return without entering one. Even giving a non-existent room id doesn't help, the only way to get rid of the dialog is to enter an actually working room id. A "Cancel" button would be nice.

**Comment by thigg** [comment]
Created an issue for it:

https://github.com/vector-im/hydrogen-web/issues/936

**Comment by thigg** [comment]
and a pr https://github.com/vector-im/hydrogen-web/pull/937

**Comment by thigg** [comment]
Thanks for the report. I'll close this, report back if you hit problems
